# environment.dev.yaml

name: SynDev
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python=3.12.3
  - mamba
  - pip
  - pyyaml=6.0.2
  - pandas=2.2.2
  - matplotlib=3.9.2
  - mygene
  - seaborn=0.13.2
  - statsmodels=0.14.2
  - scipy=1.14.0
  - scikit-learn=1.5.2
  - matplotlib-venn=1.1.1
  - upsetplot=0.9.0
  - snakemake=8.18.1
  - gseapy=1.1.3
  - r-base=4.3.3
  - r-essentials
  - bioconductor-clusterprofiler=4.10.0
