# environment.yaml

name: SynEnrich
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python=3.12.3
  - mamba
  - pip
  - pandas
  - matplotlib
  - seaborn
  - snakemake
  - gseapy
  - matplotlib-venn
  - rpy2
  - r-base=4.3.3
  - r-essentials
  - bioconductor-clusterprofiler=4.10.0
  - bioconductor-org.hs.eg.db=3.18.0
  - bioconductor-annotationdbi=1.64.1
