channels:
- conda-forge
- bioconda
- nodefaults
dependencies:
- python=3.12.3
- mamba
- pip
- pyyaml
- pandas
- matplotlib
- seaborn
- statsmodels
- scipy
- scikit-learn=1.5.2
- matplotlib-venn
- upsetplot
- snakemake
- gseapy
- rpy2
- r-base=4.3.3
- r-essentials
- bioconductor-clusterprofiler=4.10.0
- bioconductor-org.hs.eg.db=3.18.0
- bioconductor-annotationdbi=1.64.1
- isort>=5.12.0
- pre-commit>=3.5.0
- ruff>=0.1.5
- pyright>=1.1.335
- pytest>=7.4.3
- codecov>=2.1.13
- pytest-cov>=4.1.0
- pytest-benchmark>=4.0.0
- mkdocs>=1.5.3
- mkdocstrings>=0.23.0
- mkdocstrings-python>=1.7.3
- mkdocs-material>=9.4.8
- Pygments>=2.16.1
- snakemake=8.18.1
- mygene
name: SynDev
