# environment.yaml

name: SynEnrich_ClusteProfiler
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - mamba
  - r-base=4.3.3
  - r-essentials
  - bioconductor-clusterprofiler=4.10.0
  - bioconductor-org.hs.eg.db=3.18.0
  - bioconductor-org.mm.eg.db=3.18.0
  - bioconductor-annotationdbi=1.64.1
