# environment.yaml

name: SynEnrich
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - mamba
  - pip
  - pandas
  - snakemake
  - gseapy
  - r-base=4.3.3
  - r-essentials
  - bioconductor-clusterprofiler
  - bioconductor-org.hs.eg.db
